"""
Service for generating text embeddings using Sentence Transformers.
"""
from typing import List
import numpy as np
from sentence_transformers import SentenceTransformer

from ..interfaces.IEmbeddingService import IEmbeddingService


class EmbeddingService(IEmbeddingService):
    """
    Concrete implementation of IEmbeddingService using Sentence Transformers.
    Generates semantic embeddings for text classification.
    """

    def __init__(self, model_name: str = 'neuralmind/bert-base-portuguese-cased'):
        """
        Initialize the embedding service with a Sentence Transformer model.

        Args:
            model_name: Name of the pre-trained model to use.
                       Default: 'neuralmind/bert-base-portuguese-cased' (optimized for Brazilian Portuguese)
        """
        self.model_name = model_name
        self.model = SentenceTransformer(model_name)

    def generate_embeddings(self, texts: List[str]) -> np.ndarray:
        """
        Generate embeddings for a list of texts.

        Args:
            texts: List of strings to generate embeddings for

        Returns:
            numpy.ndarray: Matrix of embeddings (len(texts), embedding_dimension)
        """
        if not texts:
            return np.array([])

        embeddings = self.model.encode(
            texts,
            show_progress_bar=True,
            batch_size=32,
            normalize_embeddings=True,  # Important for cosine similarity
            convert_to_numpy=True
        )

        return embeddings

    def get_embedding_dimension(self) -> int:
        """
        Get the dimension of embeddings generated by the model.

        Returns:
            int: Dimension of embedding vectors
        """
        return self.model.get_sentence_embedding_dimension()
